name: Build and Push to AWS ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image for aarch64
      env:
        ECR_URL: "${{ steps.login-ecr.outputs.registry }}/"
        AWS_REGION: il-central-1
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t $ECR_REPOSITORY .
        docker tag $ECR_REPOSITORY:latest $ECR_URL$ECR_REPOSITORY:latest
        docker buildx build --push --platform linux/arm64 -t $ECR_URL$ECR_REPOSITORY:latest .
